server:
  port: 8010

eureka:
  instance:
    hostname: 192.168.1.86
    ip-address: 192.168.1.86
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/