server:
    port: 8011
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.86:8010/eureka/
spring:
    application:
        name: security-service
    datasource:
        name: test
        url: jdbc:mysql://192.168.1.21:3306/test
        username: adminis
        password: adminis
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
    type-aliases-package: com.spring.cloud.master.entity
    mapper-locations: classpath:mybatis/mapper/**/*.xml
security:
  oauth2:
    resource:
      filter-order: 3

